-- ORACLE

SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, A.TOTAL_SALES

FROM (

    SELECT AUTHOR.AUTHOR_ID, BOOK.CATEGORY, SUM(BOOK.PRICE * BOOK_SALES.SALES) AS TOTAL_SALES
    FROM BOOK_SALES, BOOK, AUTHOR
    WHERE 1 = 1
    AND TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
    AND BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
    AND BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    GROUP BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY

) A, AUTHOR B
WHERE 1 = 1
AND A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC;