-- ORACLE

SELECT WRITER_ID USER_ID
        , (SELECT NICKNAME FROM USED_GOODS_USER WHERE WRITER_ID = USER_ID) NICKNAME
        , SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE 1 = 1
AND STATUS = 'DONE'

GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES