-- ORACLE

WITH GOLDMEMBER AS (

    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE 1 = 1
    AND STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000

)

SELECT USED_GOODS_USER.USER_ID, USED_GOODS_USER.NICKNAME, GOLDMEMBER.TOTAL_SALES
FROM USED_GOODS_USER, GOLDMEMBER
WHERE 1 = 1
AND GOLDMEMBER.WRITER_ID = USED_GOODS_USER.USER_ID
ORDER BY 3 ASC;