-- MySQL

WITH BENCHMARK(GRADE, BONUS_RATIO) AS (
    SELECT 'S', 0.2 FROM DUAL
    UNION ALL
    SELECT 'A', 0.15 FROM DUAL
    UNION ALL
    SELECT 'B', 0.1 FROM DUAL
    UNION ALL
    SELECT 'C', 0 FROM DUAL
)

SELECT HR_EMPLOYEES.EMP_NO AS EMP_NO
      ,HR_EMPLOYEES.EMP_NAME AS EMP_NAME
      ,GRADE_INFO.GRADE AS GRADE
      ,HR_EMPLOYEES.SAL * BENCHMARK.BONUS_RATIO AS BONUS

FROM HR_EMPLOYEES, BENCHMARK, (

    SELECT EMP_NO
           , CASE WHEN AVG(SCORE) >= 96 THEN 'S'
                  WHEN AVG(SCORE) >= 90 THEN 'A'
                  WHEN AVG(SCORE) >= 80 THEN 'B'
             ELSE 'C' END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO

) GRADE_INFO

WHERE 1 = 1
AND HR_EMPLOYEES.EMP_NO = GRADE_INFO.EMP_NO
AND GRADE_INFO.GRADE = BENCHMARK.GRADE
ORDER BY 1 ASC