-- ORACLE

SELECT PRODUCT.PRODUCT_CODE AS PRODUCT_CODE, SUM(OFFLINE_SALE.SALES_AMOUNT) * MAX(PRODUCT.PRICE) AS SALES
FROM PRODUCT, OFFLINE_SALE
WHERE 1 = 1
AND PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY 2 DESC, 1 ASC;