-- ORACLE

WITH TOT_SALE AS (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOT_SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)

SELECT PRODUCT.PRODUCT_CODE, PRODUCT.PRICE * TOT_SALE.TOT_SALES_AMOUNT AS SALES
FROM PRODUCT, TOT_SALE
WHERE 1 = 1
AND PRODUCT.PRODUCT_ID = TOT_SALE.PRODUCT_ID
ORDER BY 2 DESC, 1 ASC;
