-- ORACLE

SELECT *

FROM (

    SELECT JULY.FLAVOR
    FROM JULY INNER JOIN FIRST_HALF
    ON 1 = 1
    AND JULY.FLAVOR = FIRST_HALF.FLAVOR
    GROUP BY JULY.FLAVOR
    ORDER BY SUM(JULY.TOTAL_ORDER) + SUM(FIRST_HALF.TOTAL_ORDER) DESC

)

WHERE ROWNUM <= 3