-- ORACLE

WITH JULY_TOT AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOT
    FROM JULY
    GROUP BY FLAVOR
)
, HALF_TOT AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOT
    FROM FIRST_HALF
    GROUP BY FLAVOR
)

SELECT RES.FLAVOR
FROM (

    SELECT JULY_TOT.FLAVOR AS FLAVOR, JULY_TOT.TOT + HALF_TOT.TOT AS TOTAL_SUM
    FROM JULY_TOT, HALF_TOT
    WHERE 1 = 1
    AND JULY_TOT.FLAVOR = HALF_TOT.FLAVOR
    ORDER BY 2 DESC
     
) RES
WHERE 1 = 1
AND ROWNUM <= 3