-- ORACLE

SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY

FROM (

    SELECT ITEM_TREE.ITEM_ID

    FROM ITEM_INFO, ITEM_TREE
    
    WHERE 1 = 1
    AND ITEM_INFO.RARITY = 'RARE'
    AND ITEM_TREE.PARENT_ITEM_ID = ITEM_INFO.ITEM_ID
    
) UPGRADE_ITEM, ITEM_INFO

WHERE 1 = 1
AND UPGRADE_ITEM.ITEM_ID = ITEM_INFO.ITEM_ID

ORDER BY ITEM_INFO.ITEM_ID DESC