-- ORACLE

SELECT USED_GOODS_USER.USER_ID
     , USED_GOODS_USER.NICKNAME
     , USED_GOODS_USER.CITY || ' ' || USED_GOODS_USER.STREET_ADDRESS1 || ' ' || USED_GOODS_USER.STREET_ADDRESS2 AS 전체주소
     , SUBSTR(USED_GOODS_USER.TLNO, 1, 3) || '-' || SUBSTR(USED_GOODS_USER.TLNO, 4, 4) || '-' || SUBSTR(USED_GOODS_USER.TLNO, 8, 4) AS 전화번호
     
FROM USED_GOODS_USER, (

    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) >= 3
    
) VIP

WHERE 1 = 1
AND USED_GOODS_USER.USER_ID = VIP.WRITER_ID

ORDER BY 1 DESC;