-- ORACLE

WITH INFORMATION AS (

    SELECT ICECREAM_INFO.FLAVOR, ICECREAM_INFO.INGREDIENT_TYPE, FIRST_HALF.TOTAL_ORDER
    FROM FIRST_HALF, ICECREAM_INFO
    WHERE 1 = 1
    AND FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR

)

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM INFORMATION
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;