-- ORACLE

WITH JANUARY_SALES AS (

    SELECT BOOK_ID, SUM(SALES) AS TOT_SALES
    FROM BOOK_SALES
    WHERE 1 = 1
    AND TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
    GROUP BY BOOK_ID

)

SELECT BOOK.CATEGORY AS CATEGORY, SUM(JANUARY_SALES.TOT_SALES) AS TOTAL_SALES
FROM BOOK, JANUARY_SALES
WHERE 1 = 1
AND BOOK.BOOK_ID = JANUARY_SALES.BOOK_ID
GROUP BY BOOK.CATEGORY
ORDER BY CATEGORY ASC;