-- ORACLE

SELECT BOOK.CATEGORY AS CATEGORY, SUM(BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK, BOOK_SALES
WHERE 1 = 1
AND TO_CHAR(BOOK_SALES.SALES_DATE, 'YYYY-MM') = '2022-01'
AND BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY