-- ORACLE

/*
* 3월에 태어난 여성 중에서 전화번호가 NULL이 아닌 회원을
* MEMBER_ID 오름차순으로 조회.
* 단, 회원의 생일은 'YYYY-MM-DD' 형식이어야 함.
*/

SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE 1 = 1
AND EXTRACT(MONTH FROM DATE_OF_BIRTH) = 3
AND GENDER = 'W'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;