-- ORACLE

WITH OUT_COUNT AS (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
)
, HOUR_LIST AS (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
)

SELECT HOUR_LIST.HOUR, NVL(OUT_COUNT.COUNT, 0) AS COUNT
FROM HOUR_LIST, OUT_COUNT
WHERE 1 = 1
AND HOUR_LIST.HOUR = OUT_COUNT.HOUR(+) -- LEFT OUTER JOIN
ORDER BY HOUR ASC;
