-- ORACLE

WITH RENTAL AS (

    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 1 = 1
    AND TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5

)
    

SELECT RES.MONTH AS MONTH, RES.CAR_ID, COUNT(RES.CAR_ID) AS RECORDS

FROM (

    SELECT HIS.CAR_ID AS CAR_ID, TO_NUMBER(TO_CHAR(HIS.START_DATE, 'MM')) AS MONTH
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS, RENTAL
    WHERE 1 = 1
    AND HIS.CAR_ID = RENTAL.CAR_ID
    
) RES

GROUP BY RES.MONTH, RES.CAR_ID
HAVING COUNT(RES.CAR_ID) > 0
AND RES.MONTH BETWEEN 8 AND 10

ORDER BY RES.MONTH ASC, RES.CAR_ID DESC