-- ORACLE


WITH JOINED_2021 AS (

    SELECT TO_NUMBER(TO_CHAR(ONLINE_SALE.SALES_DATE, 'YYYY')) AS YEAR
         , TO_NUMBER(TO_CHAR(ONLINE_SALE.SALES_DATE, 'MM')) AS MONTH
         , COUNT(DISTINCT ONLINE_SALE.USER_ID) OVER (PARTITION BY TO_CHAR(ONLINE_SALE.SALES_DATE, 'YYYYMM')) AS PURCHASED_USERS

    FROM USER_INFO, ONLINE_SALE
    WHERE 1 = 1
    AND TO_CHAR(USER_INFO.JOINED, 'YYYY') = '2021'
    AND USER_INFO.USER_ID = ONLINE_SALE.USER_ID

)

SELECT YEAR, MONTH, PURCHASED_USERS
       , ROUND(PURCHASED_USERS / (SELECT COUNT(*) FROM USER_INFO WHERE TO_CHAR(USER_INFO.JOINED, 'YYYY') = '2021'), 1) AS PURCHASED_RATIO
FROM JOINED_2021
GROUP BY YEAR, MONTH, PURCHASED_USERS
ORDER BY 1 ASC, 2 ASC;
