-- ORACLE

WITH USERS AS (
    SELECT DISTINCT(USER_ID) AS USER_ID
    FROM USER_INFO
    WHERE 1 = 1
    AND TO_CHAR(JOINED, 'YYYY') = '2021'
)


SELECT TO_NUMBER(TO_CHAR(ONLINE_SALE.SALES_DATE, 'YYYY')) AS YEAR
     , TO_NUMBER(TO_CHAR(ONLINE_SALE.SALES_DATE, 'MM')) AS MONTH
     , COUNT(DISTINCT(ONLINE_SALE.USER_ID)) AS PURCHASED_USERS
     , ROUND(COUNT(DISTINCT(ONLINE_SALE.USER_ID)) / (SELECT COUNT(*) FROM USERS), 1) AS PURCHASED_RATIO

FROM ONLINE_SALE, USERS
WHERE 1 = 1
AND USERS.USER_ID = ONLINE_SALE.USER_ID
GROUP BY TO_CHAR(ONLINE_SALE.SALES_DATE, 'YYYY'), TO_CHAR(ONLINE_SALE.SALES_DATE, 'MM')

ORDER BY 1 ASC, 2 ASC;