-- MySQL

SELECT COUNT(FISH_INFO.FISH_TYPE) AS FISH_COUNT, FISH_NAME_INFO.FISH_NAME
FROM FISH_NAME_INFO INNER JOIN FISH_INFO
ON 1 = 1
AND FISH_NAME_INFO.FISH_TYPE = FISH_INFO.FISH_TYPE
GROUP BY FISH_NAME_INFO.FISH_NAME
ORDER BY 1 DESC


/*
-- MySQL

SELECT COUNT(FISH_INFO.FISH_TYPE) AS FISH_COUNT, FISH_NAME_INFO.FISH_NAME
FROM FISH_INFO LEFT JOIN FISH_NAME_INFO
ON 1 = 1
AND FISH_NAME_INFO.FISH_TYPE = FISH_INFO.FISH_TYPE
GROUP BY FISH_NAME_INFO.FISH_NAME
ORDER BY 1 DESC;

위 SQL도 정답처리 됨.

*/