-- MySQL

/*

- 상식적으로 FISH_NAME_INFO 테이블의 FISH_TYPE 종류가 더 많을 수 있음.
- 그러나, COUNTING과 FISH_NAME_INFO 테이블의 LEFT JOIN 위치를 바꾸면 오답이 됨.
- 문제 혹은 데이터가 잘못 된 것으로 보임.

*/

SELECT IFNULL(COUNTING.FISH_COUNT, 0) AS FISH_COUNT, FISH_NAME_INFO.FISH_NAME

FROM (

    SELECT FISH_TYPE, COUNT(FISH_TYPE) AS FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE

) COUNTING LEFT JOIN FISH_NAME_INFO

ON 1 = 1
AND FISH_NAME_INFO.FISH_TYPE = COUNTING.FISH_TYPE
ORDER BY 1 DESC;