-- ORACLE

WITH DISCOUNT AS (
    SELECT CAR_TYPE, TO_NUMBER(REGEXP_REPLACE(DURATION_TYPE, '[^0-9]')) AS DURATION, TO_NUMBER(REGEXP_REPLACE(DISCOUNT_RATE, '[^0-9]')) AS RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE 1 = 1
    AND CAR_TYPE = '트럭'
)
, RENTAL_DAYS AS (
    SELECT CRCRH.HISTORY_ID, CRCC.CAR_ID, CRCC.CAR_TYPE, CRCC.DAILY_FEE, CRCRH.END_DATE - CRCRH.START_DATE + 1 AS RDAYS
    FROM CAR_RENTAL_COMPANY_CAR CRCC
       , CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
    WHERE 1 = 1
    AND CRCC.CAR_TYPE = '트럭'
    AND CRCRH.CAR_ID = CRCC.CAR_ID
)

SELECT RENTAL_DAYS.HISTORY_ID AS HISTORY_ID
     , ROUND(MAX(RENTAL_DAYS.RDAYS) * MAX(RENTAL_DAYS.DAILY_FEE) * (100 - MAX(NVL(DISCOUNT.RATE,0)) ) / 100) AS FEE

FROM RENTAL_DAYS LEFT OUTER JOIN DISCOUNT
ON 1 = 1
AND RENTAL_DAYS.RDAYS >= DISCOUNT.DURATION
GROUP BY RENTAL_DAYS.HISTORY_ID, RENTAL_DAYS.CAR_ID
ORDER BY 2 DESC, 1 DESC;
