-- ORACLE

WITH ORDERS AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOT_AMOUNT
    FROM FOOD_ORDER
    WHERE 1 = 1
    AND TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
    GROUP BY PRODUCT_ID
)

SELECT FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, FOOD_PRODUCT.PRICE * ORDERS.TOT_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT, ORDERS
WHERE 1 = 1
AND FOOD_PRODUCT.PRODUCT_ID = ORDERS.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC;
