-- ORACLE

SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS LEFT OUTER JOIN ANIMAL_INS
ON 1 = 1
AND ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE 1 = 1
AND ANIMAL_INS.ANIMAL_ID IS NULL
ORDER BY 1 ASC, 2 ASC