-- MySQL

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE 1 = 1
AND ITEM_INFO.ITEM_ID NOT IN (
    
    SELECT DISTINCT(PARENT_ITEM_ID)
    FROM ITEM_TREE
    WHERE 1 = 1
    AND PARENT_ITEM_ID IS NOT NULL
    
)
ORDER BY ITEM_INFO.ITEM_ID DESC;