-- ORACLE

SELECT DISTINCT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCC LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON 1 = 1
AND CRCC.CAR_ID = CRCRH.CAR_ID
WHERE 1 = 1
AND CRCC.CAR_TYPE = '세단'
AND CRCRH.CAR_ID IS NOT NULL
AND TO_CHAR(CRCRH.START_DATE, 'YYYY-MM') = '2022-10'
ORDER BY 1 DESC;
