-- ORACLE

SELECT APPOINTMENT.APNT_NO, PATIENT.PT_NAME, PATIENT.PT_NO, APPOINTMENT.MCDP_CD, DOCTOR.DR_NAME, APPOINTMENT.APNT_YMD
FROM APPOINTMENT, DOCTOR, PATIENT
WHERE 1 = 1
AND TO_CHAR(APPOINTMENT.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
AND APPOINTMENT.APNT_CNCL_YN = 'N'
AND APPOINTMENT.MCDP_CD = 'CS'
AND APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
AND APPOINTMENT.PT_NO = PATIENT.PT_NO
ORDER BY 6 ASC;