-- ORACLE

SELECT NAME, DATETIME

FROM (

    SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME, RANK() OVER (ORDER BY ANIMAL_INS.DATETIME ASC) AS R

    FROM ANIMAL_INS LEFT OUTER JOIN ANIMAL_OUTS
    ON 1 = 1
    AND ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
    WHERE 1 = 1
    AND ANIMAL_OUTS.ANIMAL_ID IS NULL
    
) RESULT

WHERE 1 = 1
AND RESULT.R <= 3
ORDER BY RESULT.R ASC