-- ORACLE

SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, TO_CHAR(BOOK.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE

FROM BOOK, AUTHOR

WHERE 1 = 1
AND BOOK.CATEGORY = '경제'
AND BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID

ORDER BY 3 ASC;