-- ORACLE

SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRODUCT_CD, FP.CATEGORY, FP.PRICE

FROM FOOD_PRODUCT FP, (
    
    SELECT MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    
) TOP_PRICE

WHERE 1 = 1
AND FP.PRICE >= TOP_PRICE.MAX_PRICE;