-- ORACLE

WITH M_FAVORITES AS (

SELECT FOOD_TYPE, MAX(FAVORITES) AS MF
FROM REST_INFO
GROUP BY FOOD_TYPE

)

SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI, M_FAVORITES
WHERE 1 = 1
AND RI.FOOD_TYPE = M_FAVORITES.FOOD_TYPE
AND RI.FAVORITES >= M_FAVORITES.MF
ORDER BY RI.FOOD_TYPE DESC