-- ORACLE

WITH RANK AS (

SELECT REST_ID, RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS R
FROM REST_INFO

)

SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI, RANK
WHERE 1 = 1
AND RANK.R = 1
AND RI.REST_ID = RANK.REST_ID
ORDER BY RI.FOOD_TYPE DESC