-- MySQL


/*
* CAR_RENTAL_COMPANY_CAR TABLE에서
* CAR_TYPE이 SUV인 것들의 평균 DAILY_FEE 구하기.
* 평균 값은 소숫점에서 반올림.
*/

SELECT ROUND(AVG(DAILY_FEE)) as AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV';