-- ORACLE

SELECT TO_NUMBER(TO_CHAR(ONLINE_SALE.SALES_DATE, 'YYYY')) AS YEAR
      ,TO_NUMBER(TO_CHAR(ONLINE_SALE.SALES_DATE, 'MM')) AS MONTH
      ,USER_INFO.GENDER AS GENDER
      ,COUNT(DISTINCT(USER_INFO.USER_ID)) AS COUNT
      
FROM USER_INFO, ONLINE_SALE
WHERE 1 = 1
AND USER_INFO.GENDER IS NOT NULL
AND USER_INFO.USER_ID = ONLINE_SALE.USER_ID
GROUP BY TO_NUMBER(TO_CHAR(ONLINE_SALE.SALES_DATE, 'YYYY'))
        ,TO_NUMBER(TO_CHAR(ONLINE_SALE.SALES_DATE, 'MM'))
        ,USER_INFO.GENDER
ORDER BY 1 ASC, 2 ASC, 3 ASC;