-- MySQL

SELECT DEPARTMENTS.DEPT_ID, DEPARTMENTS.DEPT_NAME_EN, ROUND(AVG(HR_EMPLOYEES.SAL), 0) AS AVG_SAL

FROM HR_EMPLOYEES, (

    SELECT DEPT_ID, DEPT_NAME_EN
    FROM HR_DEPARTMENT
    GROUP BY DEPT_ID, DEPT_NAME_EN
    
) DEPARTMENTS

WHERE 1 = 1
AND HR_EMPLOYEES.DEPT_ID = DEPARTMENTS.DEPT_ID
GROUP BY DEPARTMENTS.DEPT_ID, DEPARTMENTS.DEPT_NAME_EN
ORDER BY 3 DESC;