-- ORACLE

SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, CRCC.DAILY_FEE * (100 - CRCDP.DISCOUNT_RATE) * 30 / 100 AS FEE

FROM CAR_RENTAL_COMPANY_CAR CRCC

LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON 1 = 1
AND CRCC.CAR_ID = CRCRH.CAR_ID
AND TO_CHAR(CRCRH.START_DATE, 'YYYY-MM-DD') <= '2022-11-30'
AND TO_CHAR(CRCRH.END_DATE, 'YYYY-MM-DD') >= '2022-11-01'

INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
ON 1 = 1
AND CRCC.CAR_TYPE = CRCDP.CAR_TYPE
AND CRCDP.DURATION_TYPE = '30일 이상'

WHERE 1 = 1
AND CRCC.CAR_TYPE IN ('세단', 'SUV')
AND CRCRH.HISTORY_ID IS NULL
AND CRCC.DAILY_FEE * (100 - CRCDP.DISCOUNT_RATE) * 30 / 100 BETWEEN 500000 AND 1999999

ORDER BY 3 DESC, 2 ASC, 1 DESC;