-- ORACLE

WITH CARS AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE AS FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE 1 = 1
    AND CAR_TYPE IN ('세단', 'SUV')
), 

DISCOUNT AS (
    SELECT CAR_TYPE, (100 - DISCOUNT_RATE) / 100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE 1 = 1
    AND DURATION_TYPE = '30일 이상'
)

SELECT CARS.CAR_ID, CARS.CAR_TYPE, CARS.FEE * DISCOUNT.DISCOUNT_RATE * 30 AS FEE
FROM CARS, DISCOUNT
WHERE 1 = 1
AND CARS.CAR_ID NOT IN (
    SELECT DISTINCT(CAR_ID)
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE 1 = 1
        AND ('2022-11-01' BETWEEN TO_CHAR(START_DATE, 'YYYY-MM-DD') AND TO_CHAR(END_DATE, 'YYYY-MM-DD')
                OR '2022-11-31' BETWEEN TO_CHAR(START_DATE, 'YYYY-MM-DD') AND TO_CHAR(END_DATE, 'YYYY-MM-DD'))
)
AND CARS.CAR_TYPE = DISCOUNT.CAR_TYPE
AND CARS.FEE * DISCOUNT.DISCOUNT_RATE * 30 BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC;