-- ORACLE

WITH TAKING_TIME AS (
    SELECT ANIMAL_OUTS.ANIMAL_ID
         , ANIMAL_OUTS.NAME
         , RANK() OVER(ORDER BY (ANIMAL_OUTS.DATETIME - ANIMAL_INS.DATETIME) DESC) AS TTIME_RANK
    FROM ANIMAL_INS LEFT OUTER JOIN ANIMAL_OUTS
    ON 1 = 1
    AND ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
    WHERE 1 = 1
    AND ANIMAL_OUTS.ANIMAL_ID IS NOT NULL
)

SELECT ANIMAL_ID, NAME
FROM TAKING_TIME
WHERE 1 = 1
AND TTIME_RANK <= 2
ORDER BY TTIME_RANK ASC;