-- ORACLE

SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME

FROM (
    SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS R
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)

WHERE 1 = 1
AND R = 1
ORDER BY MAX_PRICE DESC