-- ORACLE
-- With no Having

SELECT A.USER_ID, A.PRODUCT_ID

FROM ONLINE_SALE A, (
    SELECT USER_ID, PRODUCT_ID, COUNT(*) AS CNT
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
) B

WHERE 1 = 1
AND B.CNT >= 2
AND A.USER_ID = B.USER_ID
AND A.PRODUCT_ID = B.PRODUCT_ID

GROUP BY A.USER_ID, A.PRODUCT_ID

ORDER BY A.USER_ID ASC, A.PRODUCT_ID DESC;