-- MySQL

SELECT FIR.ID AS ID, FNI.FISH_NAME AS FISH_NAME, FIR.LENGTH AS LENGTH

FROM FISH_NAME_INFO FNI, (

    SELECT ID, FISH_TYPE, LENGTH, RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS R
    FROM FISH_INFO

) FIR

WHERE 1 = 1
AND FIR.R = 1
AND FNI.FISH_TYPE = FIR.FISH_TYPE
ORDER BY FIR.ID ASC;