-- MySQL

SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_NAME_INFO FNI, FISH_INFO FI, (

    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    WHERE 1 = 1
    AND LENGTH IS NOT NULL
    GROUP BY FISH_TYPE

) MAX_FISH
WHERE 1 = 1
AND FI.FISH_TYPE = MAX_FISH.FISH_TYPE
AND FI.LENGTH = MAX_FISH.LENGTH
AND FI.FISH_TYPE = FNI.FISH_TYPE
ORDER BY FI.ID