-- MySQL

SELECT YEARMAX.YEAR AS YEAR, (MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID AS ID

FROM ECOLI_DATA ED, (

    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    
) YEARMAX

WHERE 1 = 1
AND YEAR(ED.DIFFERENTIATION_DATE) = YEARMAX.YEAR

ORDER BY YEARMAX.YEAR ASC, YEAR_DEV ASC;