-- MySQL

SELECT CAST(DATE_FORMAT(YM, '%Y') AS UNSIGNED) AS YEAR
       , ROUND(AVG(PM_VAL1), 2) AS 'PM10'
       , ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
FROM AIR_POLLUTION
WHERE 1 = 1
AND LOCATION2 = '수원'
GROUP BY CAST(DATE_FORMAT(YM, '%Y') AS UNSIGNED)
ORDER BY 1 ASC;