-- ORACLE

-- FIRST_HALF: PK = FLAVOR
-- ICECREAM_INFO: PK, FK = FLAVOR
-- ICECREAM_INFO.INGREDIENT_TYPE: 'sugar_based', 'fruit_based'

/*
* FIRST_HALF의 TOTAL_ORDER 가 3000보다 크면서,
* ICECREAM_INFO의 INGREDIENT_TYPE이 fruit_base인 FLAVER를
* TOTAL_ORDER 내림차순으로 정렬하여 조회.
*/

SELECT A.FLAVOR AS FLAVOR
FROM FIRST_HALF A, ICECREAM_INFO B
WHERE 1 = 1
AND A.TOTAL_ORDER > 3000
AND A.FLAVOR = B.FLAVOR
AND B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY A.TOTAL_ORDER DESC;