-- ORACLE

WITH REVIEW AS (

    SELECT *
    FROM (
        SELECT MEMBER_ID, COUNT(*) AS CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY 2 DESC
    )
    WHERE ROWNUM = 1

)

SELECT MEMBER_PROFILE.MEMBER_NAME, REST_REVIEW.REVIEW_TEXT, TO_CHAR(REST_REVIEW.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE, REST_REVIEW, REVIEW
WHERE 1 = 1
AND MEMBER_PROFILE.MEMBER_ID = REVIEW.MEMBER_ID
AND REVIEW.MEMBER_ID = REST_REVIEW.MEMBER_ID
ORDER BY 3 ASC, 2 ASC;