-- ORACLE

WITH RANKING AS (
    SELECT MEMBER_ID, RANK() OVER(ORDER BY COUNT(*) DESC) AS R
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

SELECT MEMBER_PROFILE.MEMBER_NAME, REST_REVIEW.REVIEW_TEXT, TO_CHAR(REST_REVIEW.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE, REST_REVIEW, RANKING
WHERE 1 = 1
AND RANKING.R = 1
AND RANKING.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
AND RANKING.MEMBER_ID = REST_REVIEW.MEMBER_ID
ORDER BY 3 ASC, 2 ASC;