-- MySQL

SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME
FROM ITEM_TREE, ITEM_INFO
WHERE 1 = 1
AND ITEM_TREE.PARENT_ITEM_ID IS NULL
AND ITEM_TREE.ITEM_ID = ITEM_INFO.ITEM_ID
ORDER BY ITEM_INFO.ITEM_ID ASC;