-- ORACLE

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE 1 = 1
AND ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
AND NOT ( ANIMAL_INS.SEX_UPON_INTAKE LIKE 'Spayed%'
         OR ANIMAL_INS.SEX_UPON_INTAKE LIKE 'Neutered%' )
AND ( ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE 'Spayed%'
      OR ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE 'Neutered%' )  
ORDER BY 1 ASC;