-- ORACLE

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE 1 = 1
AND ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
AND ANIMAL_INS.SEX_UPON_INTAKE <> ANIMAL_OUTS.SEX_UPON_OUTCOME
ORDER BY 1 ASC;