-- ORACLE

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE 1 = 1
AND ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID

AND NOT EXISTS (
    SELECT 1
    FROM ANIMAL_INS INS
    WHERE 1 = 1
    AND ANIMAL_INS.ANIMAL_ID = INS.ANIMAL_ID
    AND (
        INS.SEX_UPON_INTAKE LIKE 'Spayed%'
        OR INS.SEX_UPON_INTAKE LIKE 'Neutered%'
    )
)

AND EXISTS (
    SELECT 1
    FROM ANIMAL_OUTS OUTS
    WHERE 1 = 1
    AND ANIMAL_OUTS.ANIMAL_ID = OUTS.ANIMAL_ID
    AND (
        OUTS.SEX_UPON_OUTCOME LIKE 'Spayed%'
        OR OUTS.SEX_UPON_OUTCOME LIKE 'Neutered%'
    )
)
ORDER BY 1 ASC;
