-- ORACLE

SELECT ('/home/grep/src/' || USED_GOODS_FILE.BOARD_ID || '/' || USED_GOODS_FILE.FILE_ID || USED_GOODS_FILE.FILE_NAME || USED_GOODS_FILE.FILE_EXT) AS FILE_PATH

FROM USED_GOODS_FILE, (

    SELECT BOARD_ID, RANK() OVER(ORDER BY VIEWS DESC) BR
    FROM USED_GOODS_BOARD

) RANKING

WHERE 1 = 1
AND RANKING.BR = 1
AND RANKING.BOARD_ID = USED_GOODS_FILE.BOARD_ID

ORDER BY USED_GOODS_FILE.FILE_ID DESC;