-- MySQL

SELECT ED.ID, IFNULL(PARENT.CNT, 0) AS CHILD_COUNT

FROM ECOLI_DATA ED LEFT JOIN (

    SELECT PARENT_ID, COUNT(*) AS CNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID

) PARENT

ON 1 = 1
AND ED.ID = PARENT.PARENT_ID